import type { Question, TopicId } from "./questions";

const topicNames: Record<TopicId, string> = {
  values: "UK values and society",
  history: "History and traditions",
  government: "Government and the law",
  "everyday-life": "Everyday life in the UK",
};

function q(
  id: string,
  topicId: TopicId,
  prompt: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): Question {
  return {
    id: `handbook-${id}`,
    topicId,
    topic: topicNames[topicId],
    prompt,
    options,
    correctIndex,
    explanation,
  };
}

export const handbookQuestions: Question[] = [
  q(
    "values-001",
    "values",
    "What two broad requirements are needed when applying for permanent residence or citizenship?",
    [
      "Speaking and reading English, and understanding life in the UK",
      "Owning property and joining a political party",
      "Having a UK-born parent and a driving licence",
      "Completing jury service and donating blood",
    ],
    0,
    "The handbook says applicants need English language ability and a good understanding of life in the UK.",
  ),
  q(
    "values-002",
    "values",
    "What English level are Life in the UK test questions written to require?",
    ["ESOL Entry Level 1", "ESOL Entry Level 2", "ESOL Entry Level 3", "A university degree level"],
    2,
    "The questions are written so they require understanding English at ESOL Entry Level 3.",
  ),
  q(
    "values-003",
    "values",
    "What is the format of the Life in the UK test?",
    ["12 spoken questions", "24 questions", "50 essay questions", "A driving-style hazard test"],
    1,
    "The handbook states that the test consists of 24 questions about important aspects of life in the UK.",
  ),
  q(
    "values-004",
    "values",
    "Where can the Life in the UK test be taken?",
    ["At any college", "Only at a registered and approved test centre", "At a local library", "At any post office"],
    1,
    "Only certificates from registered and approved Life in the UK test centres are accepted.",
  ),
  q(
    "values-005",
    "values",
    "Which languages may be available by special arrangement for the Life in the UK test?",
    ["French or Irish", "Welsh or Scottish Gaelic", "Hindi or Urdu", "Latin or Greek"],
    1,
    "The handbook says the test is usually in English, with special arrangements for Welsh or Scottish Gaelic.",
  ),
  q(
    "values-006",
    "values",
    "Which item is one of the fundamental principles of British life?",
    ["Rule by one party", "The rule of law", "Compulsory church attendance", "Military government"],
    1,
    "The listed principles include democracy, the rule of law, individual liberty, tolerance, and community participation.",
  ),
  q(
    "values-007",
    "values",
    "Which freedom does the UK offer residents in return for respecting shared responsibilities?",
    ["Freedom from all taxation", "Freedom of belief and religion", "Freedom to ignore the law", "Freedom from jury service"],
    1,
    "The handbook lists freedom of belief and religion, speech, fair trial, and protection from unfair discrimination.",
  ),
  q(
    "values-008",
    "values",
    "Which action is listed as a responsibility of someone who wants to be a permanent resident or citizen?",
    ["Respect and obey the law", "Refuse to vote", "Avoid community contact", "Ignore environmental issues"],
    0,
    "Responsibilities include obeying the law, respecting others, treating others fairly, and looking after the local area.",
  ),
  q(
    "everyday-001",
    "everyday-life",
    "Which countries make up the United Kingdom?",
    [
      "England, Scotland, Wales and Northern Ireland",
      "England, Scotland, Wales and the Republic of Ireland",
      "Great Britain and France",
      "England, Wales, Jersey and Guernsey",
    ],
    0,
    "The UK is made up of England, Scotland, Wales and Northern Ireland.",
  ),
  q(
    "everyday-002",
    "everyday-life",
    "What does Great Britain refer to?",
    ["Only England", "England, Scotland and Wales", "The whole UK", "The British Isles"],
    1,
    "Great Britain refers to England, Scotland and Wales, not Northern Ireland.",
  ),
  q(
    "everyday-003",
    "everyday-life",
    "What are the Channel Islands and the Isle of Man called in relation to the UK?",
    ["Overseas territories", "Crown dependencies", "Devolved nations", "English counties"],
    1,
    "They are closely linked to the UK but are not part of it; they are Crown dependencies.",
  ),
  q(
    "everyday-004",
    "everyday-life",
    "Where does the UK Parliament sit?",
    ["Cardiff Bay", "Stormont", "Westminster", "Holyrood"],
    2,
    "The UK is governed by the Parliament sitting in Westminster.",
  ),
  q(
    "history-001",
    "history",
    "About how long ago did Britain become permanently separated from the continent by the Channel?",
    ["1,000 years ago", "4,000 years ago", "10,000 years ago", "100,000 years ago"],
    2,
    "The handbook says Britain became permanently separated from the continent about 10,000 years ago.",
  ),
  q(
    "history-002",
    "history",
    "Where is Stonehenge located?",
    ["Wiltshire", "Orkney", "Dorset", "Suffolk"],
    0,
    "Stonehenge still stands in what is now the English county of Wiltshire.",
  ),
  q(
    "history-003",
    "history",
    "What is Skara Brae known for?",
    [
      "A Roman fort in London",
      "A preserved prehistoric village on Orkney",
      "A Tudor palace in Wales",
      "A Norman castle in Kent",
    ],
    1,
    "Skara Brae on Orkney is described as the best preserved prehistoric village in northern Europe.",
  ),
  q(
    "history-004",
    "history",
    "When did Emperor Claudius lead the successful Roman invasion of Britain?",
    ["55 BC", "AD 43", "AD 410", "1066"],
    1,
    "Julius Caesar's invasion in 55 BC failed; Claudius led a successful invasion in AD 43.",
  ),
  q(
    "history-005",
    "history",
    "Why did Emperor Hadrian build Hadrian's Wall?",
    [
      "To keep out the Picts",
      "To divide England from Wales",
      "To mark the end of the Danelaw",
      "To protect London from fire",
    ],
    0,
    "Hadrian's Wall was built in the north of England to keep out the Picts.",
  ),
  q(
    "history-006",
    "history",
    "What happened in AD 410?",
    [
      "The Roman army left Britain",
      "The Normans conquered England",
      "Magna Carta was agreed",
      "The English Civil War began",
    ],
    0,
    "The Roman army left Britain in AD 410 to defend other parts of the Roman Empire.",
  ),
  q(
    "history-007",
    "history",
    "Which peoples invaded Britain after the Romans left?",
    ["Jutes, Angles and Saxons", "Normans, Vikings and Romans", "Picts, Celts and Franks", "Boers, Huguenots and Quakers"],
    0,
    "The Jutes, Angles and Saxons came from northern Europe after the Romans left.",
  ),
  q(
    "history-008",
    "history",
    "Who became the first Archbishop of Canterbury?",
    ["St Patrick", "St Columba", "St Augustine", "St David"],
    2,
    "St Augustine led missionaries from Rome and became the first Archbishop of Canterbury.",
  ),
  q(
    "history-009",
    "history",
    "Where did the Vikings mainly come from?",
    ["Denmark and Norway", "Spain and Portugal", "Italy and Greece", "France and Belgium"],
    0,
    "The Vikings came from Denmark and Norway.",
  ),
  q(
    "history-010",
    "history",
    "What was the Danelaw?",
    [
      "An area in the east and north of England with strong Viking settlement",
      "A law passed by the Tudors",
      "The Scottish legal code",
      "A treaty with France",
    ],
    0,
    "Many Viking invaders stayed in the east and north of England, an area known as the Danelaw.",
  ),
  q(
    "history-011",
    "history",
    "Who defeated the Vikings after the Anglo-Saxon kingdoms united?",
    ["King Alfred the Great", "William the Conqueror", "Henry VIII", "Oliver Cromwell"],
    0,
    "The Anglo-Saxon kingdoms united under King Alfred the Great, who defeated the Vikings.",
  ),
  q(
    "history-012",
    "history",
    "What happened at the Battle of Hastings in 1066?",
    [
      "William of Normandy defeated Harold and became king of England",
      "Robert the Bruce defeated the English",
      "Henry Tudor defeated Richard III",
      "The Romans conquered Britain",
    ],
    0,
    "William, Duke of Normandy, defeated Harold at the Battle of Hastings and became William the Conqueror.",
  ),
  q(
    "history-013",
    "history",
    "What was the Domesday Book?",
    [
      "A list of towns, villages, landholders and possessions after the Norman Conquest",
      "A book of church prayers written under Edward VI",
      "A record of Tudor marriages",
      "A collection of Shakespeare plays",
    ],
    0,
    "William sent people across England to list settlements, people, land ownership and animals.",
  ),
  q(
    "history-014",
    "history",
    "Which period is known as the Middle Ages or medieval period in the handbook?",
    ["AD 43 to AD 410", "1066 to about 1485", "1485 to 1603", "1837 to 1901"],
    1,
    "The period after the Norman Conquest up to about 1485 is called the Middle Ages.",
  ),
  q(
    "history-015",
    "history",
    "Which battle in 1314 kept Scotland unconquered by the English?",
    ["Battle of Bannockburn", "Battle of Bosworth Field", "Battle of Agincourt", "Battle of Trafalgar"],
    0,
    "In 1314, Robert the Bruce led the Scots to victory at the Battle of Bannockburn.",
  ),
  q(
    "history-016",
    "history",
    "What was the Pale in medieval Ireland?",
    ["An area around Dublin ruled by the English", "A Scottish clan territory", "A Welsh rebellion", "A Roman road"],
    0,
    "By 1200 the English ruled an area of Ireland around Dublin known as the Pale.",
  ),
  q(
    "history-017",
    "history",
    "Which charter of rights was agreed in 1215?",
    ["Bill of Rights", "Magna Carta", "Act of Union", "Habeas Corpus Act"],
    1,
    "Magna Carta established that even the king was subject to the law and limited royal power.",
  ),
  q(
    "history-018",
    "history",
    "What did the Black Death do in Britain in 1348?",
    [
      "Killed about a third of the population in England and similar proportions in Scotland and Wales",
      "Ended the Wars of the Roses",
      "Started the Industrial Revolution",
      "Created the United Kingdom",
    ],
    0,
    "The Black Death was one of Britain's worst disasters and caused major social and economic change.",
  ),
  q(
    "history-019",
    "history",
    "By around 1400, what language had become preferred for English official documents and the royal court?",
    ["Latin", "Norman French", "English", "Gaelic"],
    2,
    "By 1400, official documents were being written in English and it was preferred in court and Parliament.",
  ),
  q(
    "history-020",
    "history",
    "Who wrote The Canterbury Tales?",
    ["Geoffrey Chaucer", "William Caxton", "John Barbour", "William Shakespeare"],
    0,
    "Chaucer wrote The Canterbury Tales, one of the first books printed by William Caxton.",
  ),
  q(
    "history-021",
    "history",
    "Which families fought in the Wars of the Roses?",
    ["Lancaster and York", "Tudor and Stuart", "Windsor and Hanover", "Normandy and Wessex"],
    0,
    "The Wars of the Roses were fought between supporters of the House of Lancaster and the House of York.",
  ),
  q(
    "history-022",
    "history",
    "Which battle ended the Wars of the Roses in 1485?",
    ["Battle of Bosworth Field", "Battle of Waterloo", "Battle of the Somme", "Battle of Culloden"],
    0,
    "Henry Tudor defeated Richard III at Bosworth Field and became Henry VII.",
  ),
  q(
    "history-023",
    "history",
    "Why did Henry VIII establish the Church of England?",
    [
      "The Pope refused to approve his divorce from Catherine of Aragon",
      "He wanted to join the Church of Scotland",
      "Parliament abolished all churches",
      "The Spanish Armada defeated England",
    ],
    0,
    "Henry VIII broke away from Rome after the Pope refused to approve his divorce.",
  ),
  q(
    "history-024",
    "history",
    "Which wife of Henry VIII gave birth to Edward?",
    ["Anne Boleyn", "Jane Seymour", "Catherine Parr", "Anne of Cleves"],
    1,
    "Jane Seymour gave Henry VIII the son he wanted, Edward, and died shortly after the birth.",
  ),
  q(
    "history-025",
    "history",
    "What did the Act for the Government of Wales do during Henry VIII's reign?",
    [
      "Formally united Wales with England",
      "Created the Scottish Parliament",
      "Split Ireland into two countries",
      "Established the NHS",
    ],
    0,
    "During Henry VIII's reign, Wales became formally united with England.",
  ),
  q(
    "history-026",
    "history",
    "Which monarch was known as Bloody Mary?",
    ["Mary I", "Mary, Queen of Scots", "Queen Anne", "Elizabeth I"],
    0,
    "Mary I was a devout Catholic who persecuted Protestants and became known as Bloody Mary.",
  ),
  q(
    "history-027",
    "history",
    "What happened in 1588 during Elizabeth I's reign?",
    [
      "The English defeated the Spanish Armada",
      "The Act of Union created Great Britain",
      "The Great Fire destroyed London",
      "The Battle of Waterloo ended the French Wars",
    ],
    0,
    "Elizabeth I became especially popular after the Spanish Armada was defeated in 1588.",
  ),
  q(
    "history-028",
    "history",
    "Which explorer's ship, the Golden Hind, was one of the first to sail around the world?",
    ["Sir Francis Drake", "Captain James Cook", "Admiral Nelson", "Sir Walter Raleigh"],
    0,
    "Sir Francis Drake helped defeat the Spanish Armada and sailed around the world in the Golden Hind.",
  ),
  q(
    "history-029",
    "history",
    "Who wrote Hamlet, Macbeth and Romeo and Juliet?",
    ["William Shakespeare", "Robert Burns", "Dylan Thomas", "Rudyard Kipling"],
    0,
    "Shakespeare wrote many famous plays and poems and influenced the English language.",
  ),
  q(
    "history-030",
    "history",
    "Who became James I of England after Elizabeth I died?",
    ["James VI of Scotland", "Charles I", "Oliver Cromwell", "Henry VII"],
    0,
    "Elizabeth I had no children, so her cousin James VI of Scotland became James I of England.",
  ),
  q(
    "history-031",
    "history",
    "What did Charles I believe about kingship?",
    ["The Divine Right of Kings", "Universal suffrage", "Proportional representation", "Free trade"],
    0,
    "Charles I believed the king was directly appointed by God and could act without Parliament's approval.",
  ),
  q(
    "history-032",
    "history",
    "Who were the two sides in the English Civil War?",
    ["Cavaliers and Roundheads", "Tories and Whigs", "Jacobites and Chartists", "Suffragettes and Quakers"],
    0,
    "Supporters of the king were Cavaliers, and supporters of Parliament were Roundheads.",
  ),
  q(
    "history-033",
    "history",
    "What title did Oliver Cromwell hold while leading the republic?",
    ["Lord Protector", "Prime Minister", "Speaker", "Archbishop"],
    0,
    "Cromwell was recognised as leader of the republic and given the title Lord Protector.",
  ),
  q(
    "history-034",
    "history",
    "What happened in the Restoration of 1660?",
    [
      "Charles II was invited back and crowned king",
      "William and Mary replaced James II",
      "Wales was united with England",
      "The NHS was created",
    ],
    0,
    "Parliament invited Charles II back from exile, restoring the monarchy.",
  ),
  q(
    "history-035",
    "history",
    "What did the Habeas Corpus Act 1679 guarantee?",
    [
      "No one could be held prisoner unlawfully without court review",
      "All adults could vote",
      "Scotland and England became one kingdom",
      "Slavery was abolished",
    ],
    0,
    "Habeas corpus means a prisoner has the right to be brought before a court.",
  ),
  q(
    "history-036",
    "history",
    "Which scientist showed how gravity applied to the whole universe?",
    ["Isaac Newton", "Charles Darwin", "Alexander Fleming", "John Logie Baird"],
    0,
    "Newton's Principia explained gravity and many of his discoveries remain important.",
  ),
  q(
    "history-037",
    "history",
    "Why is the Glorious Revolution of 1688 important?",
    [
      "It helped guarantee Parliament's power over the monarch",
      "It created the NHS",
      "It began the Industrial Revolution",
      "It ended the First World War",
    ],
    0,
    "William and Mary took the throne and the monarch could no longer rule alone as before.",
  ),
  q(
    "history-038",
    "history",
    "What did the Bill of Rights 1689 confirm?",
    [
      "The rights of Parliament and limits of the king's power",
      "The creation of the BBC",
      "The right of every adult to vote",
      "The end of the British Empire",
    ],
    0,
    "The Bill of Rights confirmed parliamentary rights and limits on royal power.",
  ),
  q(
    "history-039",
    "history",
    "What did the Act of Union 1707 create?",
    ["The Kingdom of Great Britain", "The United Kingdom of Great Britain and Ireland", "The Commonwealth", "The European Union"],
    0,
    "The Act of Union joined England and Scotland to create the Kingdom of Great Britain.",
  ),
  q(
    "history-040",
    "history",
    "Who is regarded as the first Prime Minister?",
    ["Sir Robert Walpole", "Winston Churchill", "Clement Attlee", "David Lloyd George"],
    0,
    "Sir Robert Walpole was Prime Minister from 1721 to 1742 and is regarded as the first PM.",
  ),
  q(
    "history-041",
    "history",
    "Which battle defeated Bonnie Prince Charlie's rebellion in 1746?",
    ["Culloden", "Trafalgar", "Hastings", "Bannockburn"],
    0,
    "Charles Edward Stuart was defeated at the Battle of Culloden in 1746.",
  ),
  q(
    "history-042",
    "history",
    "What was a key idea of the Enlightenment mentioned in the handbook?",
    [
      "People should have the right to their own political and religious beliefs",
      "Only property owners should read books",
      "All newspapers should need government licences",
      "The state should dictate everyone's religion",
    ],
    0,
    "The Enlightenment emphasised political and religious freedom, an important UK principle today.",
  ),
  q(
    "history-043",
    "history",
    "What powered much of the Industrial Revolution?",
    ["Steam power and machinery", "Television and radio", "Nuclear energy", "Horse racing"],
    0,
    "Britain industrialised through machinery, steam power, mechanised agriculture and manufacturing.",
  ),
  q(
    "history-044",
    "history",
    "Who opened the first curry house in Britain and introduced shampooing?",
    ["Sake Dean Mahomet", "Richard Arkwright", "Isambard Kingdom Brunel", "Adam Smith"],
    0,
    "Sake Dean Mahomet opened the Hindoostane Coffee House in London and introduced shampooing.",
  ),
  q(
    "history-045",
    "history",
    "When was slavery abolished throughout the British Empire?",
    ["1807", "1815", "1833", "1851"],
    2,
    "The Emancipation Act abolished slavery throughout the British Empire in 1833.",
  ),
  q(
    "history-046",
    "history",
    "Who played an important part in turning public opinion against the slave trade?",
    ["William Wilberforce", "Duke of Wellington", "Sir Robert Peel", "Lord Byron"],
    0,
    "William Wilberforce and other abolitionists helped change public opinion and law.",
  ),
  q(
    "history-047",
    "history",
    "What happened in 1776 in North America?",
    [
      "Thirteen American colonies declared independence",
      "The Battle of Waterloo took place",
      "Ireland became two countries",
      "The Great Exhibition opened",
    ],
    0,
    "In 1776, 13 American colonies declared independence from Britain.",
  ),
  q(
    "history-048",
    "history",
    "Who led the British fleet at the Battle of Trafalgar?",
    ["Admiral Nelson", "Duke of Wellington", "Sir Francis Drake", "Winston Churchill"],
    0,
    "Admiral Nelson led the British fleet at Trafalgar in 1805 and was killed in the battle.",
  ),
  q(
    "history-049",
    "history",
    "What battle ended the French Wars in 1815?",
    ["Waterloo", "Trafalgar", "Agincourt", "Marston Moor"],
    0,
    "The Duke of Wellington defeated Napoleon at Waterloo in 1815.",
  ),
  q(
    "history-050",
    "history",
    "Why does the Welsh dragon not appear on the Union Flag?",
    [
      "Wales was already united with England when the first Union Flag was created",
      "Wales had no patron saint",
      "The flag was made before Wales existed",
      "Only islands can appear on the flag",
    ],
    0,
    "The first Union Flag was created from the flags of England and Scotland when Wales was already united with England.",
  ),
  q(
    "history-051",
    "history",
    "What years did Queen Victoria reign?",
    ["1837 to 1901", "1707 to 1745", "1914 to 1918", "1945 to 1951"],
    0,
    "Victoria reigned from 1837 until 1901, a period known as the Victorian Age.",
  ),
  q(
    "history-052",
    "history",
    "Who built bridges, tunnels, railways and ships, including work on the Great Western Railway?",
    ["Isambard Kingdom Brunel", "George Stephenson", "Robert Adam", "Christopher Wren"],
    0,
    "Brunel was an engineer responsible for major tunnels, bridges, railway lines and ships.",
  ),
  q(
    "history-053",
    "history",
    "What is Florence Nightingale often regarded as founding?",
    ["Modern nursing", "The BBC", "The police", "The National Trust"],
    0,
    "Nightingale improved military hospitals and established a training school for nurses.",
  ),
  q(
    "history-054",
    "history",
    "What did the Reform Act of 1832 do?",
    [
      "Increased voting rights and abolished pocket and rotten boroughs",
      "Gave women over 30 the vote",
      "Created the NHS",
      "Ended the monarchy",
    ],
    0,
    "The 1832 Reform Act increased the electorate and shifted representation towards towns and cities.",
  ),
  q(
    "history-055",
    "history",
    "Who founded the Women's Social and Political Union in 1903?",
    ["Emmeline Pankhurst", "Florence Nightingale", "Mary Seacole", "Jane Austen"],
    0,
    "Emmeline Pankhurst helped found the WSPU, whose members were called suffragettes.",
  ),
  q(
    "history-056",
    "history",
    "When were women given the vote on the same terms as men?",
    ["1918", "1928", "1945", "1969"],
    1,
    "In 1928, women were given the right to vote at age 21, the same as men at that time.",
  ),
  q(
    "history-057",
    "history",
    "What event triggered the chain of events leading to the First World War?",
    [
      "The assassination of Archduke Franz Ferdinand",
      "The invasion of Poland",
      "The Battle of Britain",
      "The Easter Rising",
    ],
    0,
    "The assassination on 28 June 1914 was the trigger for the First World War.",
  ),
  q(
    "history-058",
    "history",
    "When did the First World War end?",
    ["11.00 am on 11 November 1918", "6 June 1944", "8 May 1945", "31 January 2020"],
    0,
    "The First World War ended at 11.00 am on 11 November 1918.",
  ),
  q(
    "history-059",
    "history",
    "What was the Easter Rising?",
    [
      "An uprising against the British in Dublin in 1916",
      "A protest for women's suffrage in London",
      "A Scottish rebellion at Culloden",
      "A strike by trade unions in the 1970s",
    ],
    0,
    "Irish nationalists rose against the British in Dublin in 1916 after Home Rule was postponed.",
  ),
  q(
    "history-060",
    "history",
    "What did the 1921 peace treaty concerning Ireland lead to?",
    [
      "Ireland being split into Northern Ireland and the Irish Free State",
      "Ireland joining Scotland",
      "The abolition of Parliament",
      "The creation of the European Union",
    ],
    0,
    "The treaty split Ireland; six northern counties remained in the UK as Northern Ireland.",
  ),
  q(
    "history-061",
    "history",
    "What was the Great Depression?",
    [
      "A worldwide economic crisis beginning in 1929",
      "A Tudor religious conflict",
      "A medieval plague",
      "A battle in South Africa",
    ],
    0,
    "The world entered the Great Depression in 1929, causing mass unemployment in parts of the UK.",
  ),
  q(
    "history-062",
    "history",
    "Why did Britain and France declare war on Germany in 1939?",
    [
      "Hitler invaded Poland",
      "Germany joined NATO",
      "The Berlin Wall fell",
      "Germany left the EEC",
    ],
    0,
    "When Hitler invaded Poland in 1939, Britain and France declared war.",
  ),
  q(
    "history-063",
    "history",
    "What was the Dunkirk evacuation?",
    [
      "The rescue of more than 300,000 soldiers from beaches in France",
      "The first flight of Concorde",
      "The evacuation after the Great Fire of London",
      "The partition of Ireland",
    ],
    0,
    "Civilian volunteers and the Navy helped rescue more than 300,000 men around Dunkirk.",
  ),
  q(
    "history-064",
    "history",
    "Which planes were especially important in the Battle of Britain?",
    ["Spitfire and Hurricane", "Concorde and Harrier", "Boeing and Airbus", "Lancaster and Vulcan"],
    0,
    "The RAF used British-designed Spitfire and Hurricane fighters in the Battle of Britain.",
  ),
  q(
    "history-065",
    "history",
    "What does D-Day refer to?",
    ["Allied landings in Normandy on 6 June 1944", "The start of the NHS", "The Battle of Trafalgar", "The signing of Magna Carta"],
    0,
    "On 6 June 1944, Allied forces landed in Normandy and began the liberation of Western Europe.",
  ),
  q(
    "history-066",
    "history",
    "Who discovered penicillin in 1928?",
    ["Alexander Fleming", "Francis Crick", "John Logie Baird", "Tim Berners-Lee"],
    0,
    "Scottish doctor Alexander Fleming discovered penicillin while researching influenza.",
  ),
  q(
    "history-067",
    "history",
    "Which report provided the basis for the modern welfare state?",
    ["Beveridge Report", "Butler Report", "Good Friday Agreement", "Treaty of Rome"],
    0,
    "William Beveridge's 1942 report proposed ways to fight Want, Disease, Ignorance, Squalor and Idleness.",
  ),
  q(
    "history-068",
    "history",
    "Who led the establishment of the NHS in 1948?",
    ["Aneurin Bevan", "Harold Macmillan", "Margaret Thatcher", "R A Butler"],
    0,
    "Aneurin (Nye) Bevan, Minister for Health, led the establishment of the NHS.",
  ),
  q(
    "history-069",
    "history",
    "What did the Education Act 1944 introduce?",
    ["Free secondary education in England and Wales", "Votes for women", "The minimum driving age", "Devolution for Scotland"],
    0,
    "The Butler Act introduced free secondary education and a clear primary/secondary distinction.",
  ),
  q(
    "history-070",
    "history",
    "Which groups were encouraged to come to Britain because of post-war labour shortages?",
    [
      "Workers from Ireland, Europe, the West Indies, India, Pakistan and later Bangladesh",
      "Only Roman soldiers",
      "Only Norman nobles",
      "Only people from Australia",
    ],
    0,
    "Post-war reconstruction and labour shortages led to immigration from several regions.",
  ),
  q(
    "history-071",
    "history",
    "Which British invention was developed by John Logie Baird?",
    ["Television", "ATM", "Jet engine", "Hovercraft"],
    0,
    "John Logie Baird developed television in the 1920s.",
  ),
  q(
    "history-072",
    "history",
    "Who invented the World Wide Web?",
    ["Sir Tim Berners-Lee", "Alan Turing", "Sir Frank Whittle", "Sir Robert Watson-Watt"],
    0,
    "Sir Tim Berners-Lee invented the World Wide Web, with information first transferred via the web in 1990.",
  ),
  q(
    "history-073",
    "history",
    "When did the UK join the EEC?",
    ["1957", "1973", "1998", "2020"],
    1,
    "The UK joined the European Economic Community in 1973.",
  ),
  q(
    "history-074",
    "history",
    "Who was the UK's first woman Prime Minister?",
    ["Margaret Thatcher", "Theresa May", "Elizabeth II", "Emmeline Pankhurst"],
    0,
    "Margaret Thatcher became Prime Minister in 1979 and served until 1990.",
  ),
  q(
    "history-075",
    "history",
    "What happened in 1982 involving the Falkland Islands?",
    [
      "Argentina invaded and a UK task force recovered the islands",
      "The islands joined the EU",
      "The islands became part of Scotland",
      "The Good Friday Agreement was signed there",
    ],
    0,
    "Argentina invaded the Falkland Islands, a British overseas territory, and UK military action recovered them.",
  ),
  q(
    "history-076",
    "history",
    "What did the Good Friday Agreement of 1998 help establish?",
    ["The Northern Ireland peace process and Assembly", "The NHS", "The BBC", "The Union Flag"],
    0,
    "The agreement built on the peace process and led to the Northern Ireland Assembly.",
  ),
  q(
    "history-077",
    "history",
    "What was Brexit?",
    ["The UK's departure from the EU", "The creation of the Commonwealth", "A Scottish parliament election", "A British film award"],
    0,
    "The UK left the EU after the Brexit vote; Brexit officially took place on 31 January 2020.",
  ),
  q(
    "history-078",
    "history",
    "Which party formed the UK government after the 2024 general election in the uploaded handbook?",
    ["Labour", "Conservative", "Liberal Democrats", "Green Party"],
    0,
    "The uploaded handbook states that Labour, led by Keir Starmer, won the 2024 general election.",
  ),
  q(
    "everyday-005",
    "everyday-life",
    "What is the Proms?",
    [
      "An eight-week summer season of orchestral classical music",
      "A football league",
      "A bank holiday",
      "A court procedure",
    ],
    0,
    "The Proms is an eight-week summer classical music season organised by the BBC since 1927.",
  ),
  q(
    "everyday-006",
    "everyday-life",
    "Which composer wrote the Water Music and Messiah?",
    ["George Frederick Handel", "Gustav Holst", "Edward Elgar", "Benjamin Britten"],
    0,
    "Handel became a British citizen and wrote Water Music, Music for the Royal Fireworks and Messiah.",
  ),
  q(
    "everyday-007",
    "everyday-life",
    "Which work is Gustav Holst best known for?",
    ["The Planets", "Messiah", "Peter Grimes", "Pomp and Circumstance Marches"],
    0,
    "Holst's work includes The Planets, including Jupiter, later adapted for I Vow to Thee My Country.",
  ),
  q(
    "everyday-008",
    "everyday-life",
    "What is usually played at the Last Night of the Proms?",
    ["Land of Hope and Glory", "Auld Lang Syne", "The Daffodils", "Rule by Law"],
    0,
    "Elgar's Pomp and Circumstance March No. 1, known as Land of Hope and Glory, is usually played.",
  ),
  q(
    "everyday-009",
    "everyday-life",
    "What is the National Eisteddfod of Wales?",
    [
      "An annual Welsh cultural festival",
      "A rugby tournament",
      "A court in Cardiff",
      "A national park",
    ],
    0,
    "It is an annual cultural festival with music, dance, art and performances largely in Welsh.",
  ),
  q(
    "everyday-010",
    "everyday-life",
    "Which West End play by Agatha Christie has had the longest initial run in history?",
    ["The Mousetrap", "Cats", "The Mikado", "Evita"],
    0,
    "The Mousetrap has been running in London's West End since 1952.",
  ),
  q(
    "everyday-011",
    "everyday-life",
    "What is a pantomime?",
    [
      "A light-hearted family play with music and comedy often staged at Christmas",
      "A serious court hearing",
      "A Scottish parliamentary debate",
      "A national census",
    ],
    0,
    "Pantomimes are Christmas theatre traditions based on fairy stories, with comedy and music.",
  ),
  q(
    "everyday-012",
    "everyday-life",
    "What is the Edinburgh Festival Fringe mainly known for?",
    ["Theatre and comedy performances", "Horse racing", "General elections", "Food markets"],
    0,
    "The Fringe is the largest and best-known Edinburgh festival, showcasing mainly theatre and comedy.",
  ),
  q(
    "everyday-013",
    "everyday-life",
    "Which prize celebrates contemporary art and is named after Joseph Turner?",
    ["Turner Prize", "Man Booker Prize", "Mercury Music Prize", "Olivier Award"],
    0,
    "The Turner Prize was established in 1984 and is one of Europe's prestigious visual art awards.",
  ),
  q(
    "everyday-014",
    "everyday-life",
    "Who designed the new St Paul's Cathedral after the Great Fire of London?",
    ["Sir Christopher Wren", "Inigo Jones", "Robert Adam", "Sir Edwin Lutyens"],
    0,
    "Sir Christopher Wren designed the new St Paul's Cathedral.",
  ),
  q(
    "everyday-015",
    "everyday-life",
    "What is the Cenotaph in Whitehall associated with?",
    ["The annual Remembrance Day service", "The Chelsea Flower Show", "The Proms", "The Turner Prize"],
    0,
    "The Cenotaph is the site of the annual Remembrance Day service.",
  ),
  q(
    "everyday-016",
    "everyday-life",
    "Which novel was voted the country's best-loved novel in 2003?",
    ["The Lord of the Rings", "Lucky Jim", "Brighton Rock", "Treasure Island"],
    0,
    "The Lord of the Rings by JRR Tolkien was voted the country's best-loved novel in 2003.",
  ),
  q(
    "everyday-017",
    "everyday-life",
    "Who created Sherlock Holmes?",
    ["Sir Arthur Conan Doyle", "Charles Dickens", "Ian Fleming", "Robert Louis Stevenson"],
    0,
    "Sir Arthur Conan Doyle was a Scottish doctor and writer known for Sherlock Holmes.",
  ),
  q(
    "everyday-018",
    "everyday-life",
    "Which poet wrote The Tyger?",
    ["William Blake", "Lord Byron", "William Wordsworth", "Wilfred Owen"],
    0,
    "The famous lines 'Tyger! Tyger! Burning bright' are from William Blake's The Tyger.",
  ),
  q(
    "everyday-019",
    "everyday-life",
    "What does Christmas Day celebrate?",
    ["The birth of Jesus Christ", "The end of Ramadan", "The founding of the Khalsa", "The Battle of the Boyne"],
    0,
    "Christmas Day on 25 December celebrates the birth of Jesus Christ.",
  ),
  q(
    "everyday-020",
    "everyday-life",
    "What is Diwali often called?",
    ["The Festival of Lights", "Pancake Day", "Hogmanay", "Remembrance Day"],
    0,
    "Diwali is often called the Festival of Lights and is celebrated by Hindus and Sikhs.",
  ),
  q(
    "everyday-021",
    "everyday-life",
    "What does Eid al-Fitr celebrate?",
    ["The end of Ramadan", "The birth of Jesus", "The founding of the Sikh Khalsa", "The beginning of Lent"],
    0,
    "Eid al-Fitr marks the end of Ramadan, after a month of fasting.",
  ),
  q(
    "everyday-022",
    "everyday-life",
    "What does Vaisakhi celebrate?",
    ["The founding of the Sikh community known as the Khalsa", "The Jewish struggle for religious freedom", "The end of the First World War", "The start of winter"],
    0,
    "Vaisakhi, also spelled Baisakhi, celebrates the founding of the Khalsa.",
  ),
  q(
    "everyday-023",
    "everyday-life",
    "What is Hogmanay?",
    ["New Year in Scotland", "A Welsh food", "A Northern Irish court", "An English football cup"],
    0,
    "In Scotland, 31 December is called Hogmanay and 2 January is also a public holiday.",
  ),
  q(
    "everyday-024",
    "everyday-life",
    "What is Bonfire Night connected with?",
    [
      "Guy Fawkes and the failed 1605 plot to bomb Parliament",
      "The first television broadcast",
      "The founding of the NHS",
      "The signing of Magna Carta",
    ],
    0,
    "Bonfire Night on 5 November remembers the failed plot led by Guy Fawkes.",
  ),
  q(
    "everyday-025",
    "everyday-life",
    "Which flower is worn on Remembrance Day?",
    ["Poppy", "Rose", "Daffodil", "Thistle"],
    0,
    "People wear poppies to commemorate those who died fighting for the UK and its allies.",
  ),
  q(
    "everyday-026",
    "everyday-life",
    "What is an allotment?",
    ["Additional rented land used to grow fruit and vegetables", "A bank holiday", "A parliamentary seat", "A court verdict"],
    0,
    "Some people rent allotments to grow fruit and vegetables.",
  ),
  q(
    "everyday-027",
    "everyday-life",
    "Which traditional food is associated with Scotland?",
    ["Haggis", "Welsh cakes", "Ulster fry", "Yorkshire pudding"],
    0,
    "Haggis is traditionally associated with Scotland.",
  ),
  q(
    "everyday-028",
    "everyday-life",
    "Who was famous for playing a tramp character in silent movies?",
    ["Charlie Chaplin", "Alfred Hitchcock", "Ridley Scott", "Nick Park"],
    0,
    "Charlie Chaplin became famous in silent movies for his tramp character.",
  ),
  q(
    "everyday-029",
    "everyday-life",
    "What are the BAFTAs?",
    [
      "British Academy Film Awards",
      "British athletics finals",
      "Bank holiday theatre awards",
      "BBC radio licences",
    ],
    0,
    "The British Academy Film Awards are hosted by BAFTA and are the British equivalent of the Oscars.",
  ),
  q(
    "everyday-030",
    "everyday-life",
    "What does a UK television licence fund?",
    ["The BBC", "The NHS", "The police", "The National Trust"],
    0,
    "TV licence money funds the BBC, a public service broadcaster independent of government.",
  ),
  q(
    "everyday-031",
    "everyday-life",
    "What is the usual minimum age to buy alcohol in a pub or night club?",
    ["16", "17", "18", "21"],
    2,
    "You must be 18 or over to buy alcohol in a pub or night club.",
  ),
  q(
    "everyday-032",
    "everyday-life",
    "What must dogs wear in public places?",
    [
      "A collar showing the owner's name and address",
      "A numbered football shirt",
      "A TV licence tag",
      "A polling card",
    ],
    0,
    "Dogs in public places must wear a collar showing the owner's name and address.",
  ),
  q(
    "everyday-033",
    "everyday-life",
    "What is Big Ben?",
    ["The nickname for the great bell of the clock at the Houses of Parliament", "A Scottish castle", "A Welsh mountain", "A public holiday"],
    0,
    "Big Ben is the nickname for the great bell; many people also use it for the clock.",
  ),
  q(
    "everyday-034",
    "everyday-life",
    "Where is the Eden Project located?",
    ["Cornwall", "Edinburgh", "Belfast", "Cardiff"],
    0,
    "The Eden Project is in Cornwall in south-west England.",
  ),
  q(
    "everyday-035",
    "everyday-life",
    "What is the Giant's Causeway?",
    [
      "A Northern Ireland land formation of volcanic columns",
      "A London theatre",
      "A Welsh legal system",
      "A Scottish parliament building",
    ],
    0,
    "The Giant's Causeway is on the north-east coast of Northern Ireland and was formed from volcanic lava.",
  ),
  q(
    "everyday-036",
    "everyday-life",
    "What is Snowdon?",
    ["The highest mountain in Wales", "The largest lake in England", "A palace in London", "A Scottish poet"],
    0,
    "Snowdon is the best-known landmark in Snowdonia and is the highest mountain in Wales.",
  ),
  q(
    "everyday-037",
    "everyday-life",
    "What can visitors see at the Tower of London?",
    ["The Crown Jewels", "The Book of Common Prayer", "The Bayeux Tapestry", "The Great Exhibition"],
    0,
    "The Tower of London has Yeoman Warder tours and the Crown Jewels.",
  ),
  q(
    "everyday-038",
    "everyday-life",
    "What is Windermere?",
    [
      "The biggest stretch of water in the Lake District",
      "A Welsh city",
      "A Northern Irish assembly",
      "A court in Scotland",
    ],
    0,
    "Windermere is the biggest stretch of water in England's Lake District.",
  ),
  q(
    "everyday-039",
    "everyday-life",
    "Which church is the established Church in England?",
    ["Church of England", "Church of Scotland", "Roman Catholic Church", "Methodist Church"],
    0,
    "The Church of England is the official Church of the state in England.",
  ),
  q(
    "everyday-040",
    "everyday-life",
    "Who is the spiritual leader of the Church of England?",
    ["Archbishop of Canterbury", "Moderator", "Prime Minister", "Speaker"],
    0,
    "The Archbishop of Canterbury is the spiritual leader of the Church of England.",
  ),
  q(
    "everyday-041",
    "everyday-life",
    "Which national Church is Presbyterian?",
    ["Church of Scotland", "Church of England", "Church in Wales", "Church of Ireland"],
    0,
    "The Church of Scotland is a Presbyterian Church governed by ministers and elders.",
  ),
  q(
    "everyday-042",
    "everyday-life",
    "Which patron saint is associated with Wales?",
    ["St David", "St George", "St Andrew", "St Patrick"],
    0,
    "St David's Day is on 1 March and is associated with Wales.",
  ),
  q(
    "everyday-043",
    "everyday-life",
    "How many times has the UK hosted the Olympic Games according to the handbook?",
    ["Once", "Twice", "Three times", "Five times"],
    2,
    "The UK hosted the Olympics in 1908, 1948 and 2012.",
  ),
  q(
    "everyday-044",
    "everyday-life",
    "Who was the first man to run a mile in under four minutes?",
    ["Sir Roger Bannister", "Sir Steve Redgrave", "Sir Chris Hoy", "Mo Farah"],
    0,
    "Sir Roger Bannister ran the first sub-four-minute mile in 1954.",
  ),
  q(
    "everyday-045",
    "everyday-life",
    "Who captained England's 1966 World Cup-winning football team?",
    ["Bobby Moore", "Sir Ian Botham", "Andy Murray", "Bradley Wiggins"],
    0,
    "Bobby Moore captained the England football team that won the World Cup in 1966.",
  ),
  q(
    "everyday-046",
    "everyday-life",
    "What is the Ashes?",
    ["A cricket Test series between England and Australia", "A rugby league", "A golf tournament", "A horse race"],
    0,
    "The Ashes is the famous series of Test matches between England and Australia.",
  ),
  q(
    "everyday-047",
    "everyday-life",
    "Where can the modern game of golf be traced back to?",
    ["15th century Scotland", "Roman London", "19th century Wales", "Norman Ireland"],
    0,
    "The modern game of golf can be traced back to 15th century Scotland.",
  ),
  q(
    "everyday-048",
    "everyday-life",
    "Which tennis tournament is the oldest in the world and played on grass?",
    ["Wimbledon", "US Open", "French Open", "Australian Open"],
    0,
    "The Wimbledon Championships are the oldest tennis tournament and the only Grand Slam on grass.",
  ),
  q(
    "everyday-049",
    "everyday-life",
    "What is the capital city of Scotland?",
    ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"],
    0,
    "Edinburgh is the capital city of Scotland.",
  ),
  q(
    "everyday-050",
    "everyday-life",
    "What is the capital city of Northern Ireland?",
    ["Belfast", "Cardiff", "Swansea", "Liverpool"],
    0,
    "Belfast is the capital city of Northern Ireland.",
  ),
  q(
    "everyday-051",
    "everyday-life",
    "What is the currency of the UK?",
    ["Pound sterling", "Euro", "Dollar", "Franc"],
    0,
    "The UK currency is the pound sterling, with 100 pence in a pound.",
  ),
  q(
    "everyday-052",
    "everyday-life",
    "Which part of the UK makes up about 84% of the population?",
    ["England", "Scotland", "Wales", "Northern Ireland"],
    0,
    "The handbook says England makes up about 84% of the UK population.",
  ),
  q(
    "everyday-053",
    "everyday-life",
    "Which language is widely spoken and taught in Wales alongside English?",
    ["Welsh", "Irish Gaelic", "French", "Latin"],
    0,
    "Many people in Wales speak Welsh, a language different from English, and it is taught in schools and universities.",
  ),
  q(
    "everyday-054",
    "everyday-life",
    "What does UK equality law require regarding men and women?",
    [
      "They must not be discriminated against because of gender or marital status",
      "Only men may own property",
      "Only women may study at university",
      "Married women must leave work",
    ],
    0,
    "UK law gives men and women equal rights to work, own property, marry and divorce.",
  ),
  q(
    "government-001",
    "government",
    "What is democracy?",
    [
      "A system where the adult population has a say directly or through representatives",
      "Rule only by judges",
      "Rule by inherited title alone",
      "Government by newspapers",
    ],
    0,
    "Democracy means people have a say, either by direct voting or choosing representatives.",
  ),
  q(
    "government-002",
    "government",
    "What did the Chartists campaign for?",
    ["Political reform including wider voting rights", "The end of all courts", "A new royal family", "A national lottery"],
    0,
    "The Chartists campaigned for reforms such as votes for men, secret ballots and paid MPs.",
  ),
  q(
    "government-003",
    "government",
    "When was the voting age reduced to 18 for men and women?",
    ["1832", "1918", "1928", "1969"],
    3,
    "The voting age was reduced to 18 for men and women in 1969.",
  ),
  q(
    "government-004",
    "government",
    "How is the British constitution described?",
    ["Unwritten", "A single document like the US Constitution", "A royal diary", "A court verdict"],
    0,
    "The British constitution is not written down in a single document and is described as unwritten.",
  ),
  q(
    "government-005",
    "government",
    "What is the monarch's role in the UK constitution?",
    [
      "Head of state in a constitutional monarchy",
      "Leader of the opposition",
      "Speaker of the House of Commons",
      "Chief Constable",
    ],
    0,
    "The monarch is head of state but does not rule the country day to day.",
  ),
  q(
    "government-006",
    "government",
    "Who does the monarch usually invite to become Prime Minister?",
    [
      "The leader of the party with the largest number of MPs or of a coalition",
      "The oldest member of the House of Lords",
      "The Chief Justice",
      "The Mayor of London",
    ],
    0,
    "The monarch invites the leader who can form a government after an election.",
  ),
  q(
    "government-007",
    "government",
    "Who has been sovereign since 2022 according to the uploaded handbook?",
    ["King Charles III", "Queen Elizabeth II", "Prince William", "King George VI"],
    0,
    "The uploaded handbook states that King Charles III has been sovereign since 2022.",
  ),
  q(
    "government-008",
    "government",
    "What is the UK National Anthem?",
    ["God Save the King", "Land of Hope and Glory", "Auld Lang Syne", "Rule Britannia"],
    0,
    "The National Anthem is God Save the King, or God Save the Queen when the monarch is female.",
  ),
  q(
    "government-009",
    "government",
    "How are MPs elected to the House of Commons?",
    [
      "By voters in parliamentary constituencies",
      "By appointment from the monarch",
      "By selection from the House of Lords",
      "By random jury service",
    ],
    0,
    "Voters in each constituency elect an MP in a general election.",
  ),
  q(
    "government-010",
    "government",
    "Why is the House of Commons regarded as the more important chamber?",
    [
      "Its members are democratically elected",
      "Its members inherit titles",
      "It meets in Scotland",
      "It chooses judges directly",
    ],
    0,
    "The Commons is elected and the Prime Minister and most cabinet members are MPs.",
  ),
  q(
    "government-011",
    "government",
    "What are members of the House of Lords known as?",
    ["Peers", "MSPs", "AMs", "PCCs"],
    0,
    "Members of the House of Lords are known as peers.",
  ),
  q(
    "government-012",
    "government",
    "What is a life peer?",
    [
      "A member of the House of Lords appointed for their own lifetime",
      "A judge selected for a single trial",
      "An MP elected for five years",
      "A hereditary monarch",
    ],
    0,
    "Since 1958, life peers can be appointed for their own lifetime on advice including the Prime Minister's.",
  ),
  q(
    "government-013",
    "government",
    "What does the Speaker of the House of Commons do?",
    ["Chairs debates and keeps order neutrally", "Leads the governing party", "Commands the army", "Runs the NHS"],
    0,
    "The Speaker is neutral, chairs debates and ensures parliamentary rules are followed.",
  ),
  q(
    "government-014",
    "government",
    "How often must a UK general election be held at least?",
    ["Every three years", "Every four years", "Every five years", "Every ten years"],
    2,
    "MPs are elected at a general election, which is held at least every five years.",
  ),
  q(
    "government-015",
    "government",
    "What is the UK system for electing MPs called?",
    ["First past the post", "Single transferable vote", "Lottery selection", "Jury appointment"],
    0,
    "In each constituency, the candidate with the most votes is elected under first past the post.",
  ),
  q(
    "government-016",
    "government",
    "Which Act incorporated the European Convention on Human Rights into UK law?",
    ["Human Rights Act 1998", "Magna Carta", "Reform Act 1832", "Act of Union 1707"],
    0,
    "The Human Rights Act 1998 incorporated Convention principles into UK law.",
  ),
  q(
    "government-017",
    "government",
    "Which is a principle in the European Convention on Human Rights?",
    ["Right to a fair trial", "Right to avoid all taxes", "Right to choose any court verdict", "Right to drive at any age"],
    0,
    "Convention principles include the right to life, fair trial, liberty, religion and expression.",
  ),
  q(
    "government-018",
    "government",
    "Which statement about forced marriage is correct in the UK?",
    [
      "Forcing another person to marry is a criminal offence",
      "It is always acceptable if parents arrange it",
      "It only matters if both people are under 18",
      "It is treated as a civil parking offence",
    ],
    0,
    "Marriage should be entered into with full and free consent; forced marriage is a criminal offence.",
  ),
  q(
    "government-019",
    "government",
    "What does PAYE stand for?",
    ["Pay As You Earn", "Public Advice Year End", "Parliamentary Account for Young Employees", "Police and Youth Engagement"],
    0,
    "For most employees, income tax is taken automatically through Pay As You Earn.",
  ),
  q(
    "government-020",
    "government",
    "What are National Insurance Contributions used to help pay for?",
    ["State benefits and services such as the state pension and NHS", "Only foreign embassies", "Only private clubs", "Political party campaigns"],
    0,
    "National Insurance funds state benefits and services including the state retirement pension and NHS.",
  ),
  q(
    "government-021",
    "government",
    "What does a National Insurance number do?",
    [
      "Records tax and National Insurance contributions against your name",
      "Proves the right to work on its own",
      "Acts as a passport",
      "Replaces a driving licence",
    ],
    0,
    "A National Insurance number is a unique account number for recording contributions and tax.",
  ),
  q(
    "government-022",
    "government",
    "What is the minimum age to drive a car or motorcycle on public roads in the UK?",
    ["16", "17", "18", "21"],
    1,
    "You must usually be at least 17 to drive a car or motorcycle and have a driving licence.",
  ),
  q(
    "government-023",
    "government",
    "How often must a car over three years old normally have an MOT test?",
    ["Every month", "Every six months", "Every year", "Every five years"],
    2,
    "Vehicles over three years old must normally have an annual MOT test.",
  ),
  q(
    "government-024",
    "government",
    "What is criminal law concerned with?",
    ["Crimes investigated and punished through the courts", "Only landlord repairs", "Only faulty goods", "Only divorce paperwork"],
    0,
    "Criminal law relates to crimes investigated by the police or other authorities and punished by courts.",
  ),
  q(
    "government-025",
    "government",
    "Which is an example of civil law?",
    ["A dispute between landlord and tenant over repairs", "Selling tobacco to a child", "Carrying a weapon", "Selling illegal drugs"],
    0,
    "Civil law settles disputes such as housing, consumer, employment and debt cases.",
  ),
  q(
    "government-026",
    "government",
    "What is one duty of the police in the UK?",
    ["Prevent and detect crime", "Write party manifestos", "Choose the Prime Minister", "Appoint bishops"],
    0,
    "Police duties include protecting life and property, keeping the peace and preventing and detecting crime.",
  ),
  q(
    "government-027",
    "government",
    "Who sets local police priorities and budgets in England and Wales?",
    ["Police and Crime Commissioners", "The Speaker", "The Archbishop of Canterbury", "The BBC"],
    0,
    "Police and Crime Commissioners are directly elected and set local police priorities and budgets.",
  ),
  q(
    "government-028",
    "government",
    "What is the judiciary responsible for?",
    ["Interpreting the law and ensuring fair trials", "Selecting all MPs", "Running political parties", "Broadcasting Parliament"],
    0,
    "Judges interpret law, ensure fair trials and can require public bodies to change unlawful actions.",
  ),
  q(
    "government-029",
    "government",
    "Where are most minor criminal cases heard in England, Wales and Northern Ireland?",
    ["Magistrates' Court", "Crown Court", "Court of Session", "House of Lords"],
    0,
    "Most minor criminal cases are dealt with in a Magistrates' Court.",
  ),
  q(
    "government-030",
    "government",
    "How many members does a jury have in Scotland?",
    ["10", "12", "15", "20"],
    2,
    "A jury has 15 members in Scotland and 12 in England, Wales and Northern Ireland.",
  ),
  q(
    "government-031",
    "government",
    "Which verdict is possible in Scotland as well as guilty and not guilty?",
    ["Not proven", "Not heard", "Not counted", "Not selected"],
    0,
    "In Scotland, juries may return a third verdict of not proven.",
  ),
  q(
    "government-032",
    "government",
    "What does the small claims procedure help people do?",
    [
      "Settle minor disputes without spending lots of time and money on lawyers",
      "Apply for citizenship",
      "Choose the monarch",
      "Register a political party",
    ],
    0,
    "Small claims are an informal way to settle lower-value civil disputes.",
  ),
  q(
    "government-033",
    "government",
    "Where is the Prime Minister's official home?",
    ["10 Downing Street", "Buckingham Palace", "Chequers", "Holyrood"],
    0,
    "The official home of the Prime Minister is 10 Downing Street in central London.",
  ),
  q(
    "government-034",
    "government",
    "What does the Chancellor of the Exchequer have responsibility for?",
    ["The economy", "Foreign relationships", "Police and immigration", "Parliamentary debates"],
    0,
    "The Chancellor is the senior minister responsible for the economy.",
  ),
  q(
    "government-035",
    "government",
    "What is the shadow cabinet?",
    [
      "Senior opposition MPs who challenge the government and offer alternative policies",
      "The monarch's advisers",
      "The judges of the Supreme Court",
      "Local police leaders",
    ],
    0,
    "The leader of the opposition appoints shadow ministers who form the shadow cabinet.",
  ),
  q(
    "government-036",
    "government",
    "Which values are civil servants expected to follow?",
    ["Integrity, honesty, objectivity and impartiality", "Profit, secrecy, party loyalty and campaigning", "Ceremony, inheritance, ownership and wealth", "Speed, sport, music and art"],
    0,
    "Civil servants are politically neutral and expected to uphold integrity, honesty, objectivity and impartiality.",
  ),
  q(
    "government-037",
    "government",
    "Which public services are often controlled by devolved administrations?",
    ["Education and health", "Defence and foreign affairs", "Immigration and national taxation", "The monarchy and armed forces"],
    0,
    "Many services such as education are devolved, while defence and foreign affairs remain central UK matters.",
  ),
  q(
    "government-038",
    "government",
    "How many members are in the Scottish Parliament?",
    ["60", "90", "129", "650"],
    2,
    "The Scottish Parliament has 129 MSPs.",
  ),
  q(
    "government-039",
    "government",
    "What are members of the Northern Ireland Assembly called?",
    ["MLAs", "MSPs", "AMs", "MPs"],
    0,
    "Northern Ireland Assembly members are known as MLAs.",
  ),
  q(
    "government-040",
    "government",
    "What is Hansard?",
    ["The official report of proceedings in Parliament", "A tax form", "A police rank", "A court verdict"],
    0,
    "Parliamentary proceedings are published in official reports called Hansard.",
  ),
  q(
    "government-041",
    "government",
    "Who can vote in all public elections if resident in the UK?",
    [
      "Adult UK citizens and citizens of the Commonwealth and Irish Republic",
      "Only hereditary peers",
      "Anyone visiting the UK",
      "Only people who own property",
    ],
    0,
    "Adult UK citizens and resident Commonwealth and Irish citizens can vote in all public elections.",
  ),
  q(
    "government-042",
    "government",
    "What must you be on to vote in parliamentary, local or European elections?",
    ["The electoral register", "The TV licence list", "The National Trust", "A jury panel"],
    0,
    "Eligible voters must have their name on the electoral register.",
  ),
  q(
    "government-043",
    "government",
    "What are polling stations open from and until on election day?",
    ["7.00 am to 10.00 pm", "8.00 am to 6.00 pm", "9.00 am to 5.00 pm", "10.00 am to midnight"],
    0,
    "Polling stations are open from 7.00 am until 10.00 pm.",
  ),
  q(
    "government-044",
    "government",
    "Which people are generally excluded from standing for public office?",
    [
      "Members of the armed forces, civil servants and some people convicted of certain offences",
      "All parents",
      "All renters",
      "All people over 70",
    ],
    0,
    "Most UK, Irish and Commonwealth citizens over 18 can stand, with exceptions including armed forces and civil servants.",
  ),
  q(
    "government-045",
    "government",
    "What is the Commonwealth?",
    [
      "A voluntary association of countries supporting shared goals in democracy and development",
      "A court of the European Union",
      "A UK police force",
      "The name of the Welsh government",
    ],
    0,
    "The Commonwealth is a voluntary association whose members work toward shared goals.",
  ),
  q(
    "government-046",
    "government",
    "What organisation was set up after the Second World War to promote international peace and security?",
    ["United Nations", "National Trust", "BAFTA", "BBC"],
    0,
    "The United Nations was set up after the Second World War and has more than 190 members.",
  ),
  q(
    "government-047",
    "government",
    "What is NATO?",
    [
      "A group of European and North American countries that agree to help each other if attacked",
      "A British film award",
      "A Welsh cultural festival",
      "A local council tax system",
    ],
    0,
    "NATO is a defence alliance that also aims to maintain peace among its members.",
  ),
  q(
    "government-048",
    "government",
    "Who can be randomly selected for jury service from the electoral register?",
    ["People aged 18 to 70", "Only MPs", "Only lawyers", "Only people over 75"],
    0,
    "People on the electoral register aged 18 to 70 can be asked to do jury service.",
  ),
  q(
    "government-049",
    "government",
    "What are the three key roles of school governors and school boards?",
    [
      "Strategic direction, accountability, and monitoring school performance",
      "Tax collection, policing, and defence",
      "Writing exams, appointing MPs, and running courts",
      "Broadcasting, publishing, and licensing pubs",
    ],
    0,
    "Governors and school boards set strategy, ensure accountability, and monitor and evaluate performance.",
  ),
  q(
    "government-050",
    "government",
    "What is canvassing?",
    [
      "Persuading people to vote for a candidate, often by leaflets or doorstep conversations",
      "Serving on a jury",
      "Applying for a driving licence",
      "Donating blood",
    ],
    0,
    "Political party members may canvass by giving out leaflets or knocking on doors.",
  ),
  q(
    "government-051",
    "government",
    "How long does giving blood usually take according to the handbook?",
    ["About an hour", "A whole day", "One week", "Five minutes"],
    0,
    "The handbook says giving blood only takes about an hour.",
  ),
  q(
    "government-052",
    "government",
    "Which programme gives 16- and 17-year-olds opportunities for activities, skills and community projects?",
    ["National Citizen Service", "National Insurance", "NATO", "Hansard"],
    0,
    "The National Citizen Service gives 16- and 17-year-olds these opportunities.",
  ),
  q(
    "government-053",
    "government",
    "Why is recycling encouraged?",
    [
      "It uses less energy, reduces raw-material extraction and reduces landfill",
      "It replaces voting",
      "It avoids all taxes",
      "It allows driving without insurance",
    ],
    0,
    "Recycling helps save energy and raw materials and reduces rubbish sent to landfill.",
  ),
  q(
    "government-054",
    "government",
    "How can shopping locally help the environment?",
    [
      "It supports local businesses and can reduce the carbon footprint of transported goods",
      "It removes the need for councils",
      "It lets people ignore recycling",
      "It is required before voting",
    ],
    0,
    "Local shopping can support local producers and reduce how far goods travel.",
  ),
];
