import { handbookQuestions } from "./handbookQuestions";

export type TopicId = "values" | "history" | "government" | "everyday-life";

export type Question = {
  id: string;
  topicId: TopicId;
  topic: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

export const topics: Array<{ id: TopicId; name: string; description: string }> = [
  {
    id: "values",
    name: "UK values and society",
    description: "Democracy, rule of law, individual liberty, tolerance, and community life.",
  },
  {
    id: "history",
    name: "History and traditions",
    description: "Key events, historic documents, national symbols, and cultural milestones.",
  },
  {
    id: "government",
    name: "Government and the law",
    description: "Parliament, elections, devolved government, courts, and civic duties.",
  },
  {
    id: "everyday-life",
    name: "Everyday life in the UK",
    description: "Public services, geography, education, work, charities, and customs.",
  },
];

const starterQuestions: Question[] = [
  {
    id: "values-001",
    topicId: "values",
    topic: "UK values and society",
    prompt: "Which principle means that everyone, including the government, must obey the law?",
    options: ["Individual liberty", "The rule of law", "Mutual tolerance", "Representative sport"],
    correctIndex: 1,
    explanation: "The rule of law means laws apply to everyone and disputes are settled through legal processes.",
  },
  {
    id: "values-002",
    topicId: "values",
    topic: "UK values and society",
    prompt: "Which of these is a responsibility of people living in the UK?",
    options: [
      "Ignoring local laws if they differ from personal beliefs",
      "Respecting the rights and freedoms of others",
      "Voting in every local election by law",
      "Joining a political party",
    ],
    correctIndex: 1,
    explanation: "Respecting other people's rights, freedoms, and beliefs is central to life in the UK.",
  },
  {
    id: "values-003",
    topicId: "values",
    topic: "UK values and society",
    prompt: "What does freedom of speech allow people to do?",
    options: [
      "Express lawful opinions, even when others disagree",
      "Say anything without legal limits",
      "Avoid all criticism from others",
      "Publish private information about anyone",
    ],
    correctIndex: 0,
    explanation: "Freedom of speech protects lawful expression, but it does not remove laws on threats, harassment, or hate crime.",
  },
  {
    id: "values-004",
    topicId: "values",
    topic: "UK values and society",
    prompt: "Which action best shows taking part in community life?",
    options: [
      "Volunteering with a local charity",
      "Refusing to speak to neighbours",
      "Avoiding all public services",
      "Only following national news from abroad",
    ],
    correctIndex: 0,
    explanation: "Volunteering and helping local organisations are common ways to support the community.",
  },
  {
    id: "values-005",
    topicId: "values",
    topic: "UK values and society",
    prompt: "What is meant by religious tolerance in the UK?",
    options: [
      "Only one religion can be practised publicly",
      "People may follow different religions or none, within the law",
      "Religious beliefs always override UK law",
      "Religion is banned from public discussion",
    ],
    correctIndex: 1,
    explanation: "People in the UK may practise different faiths, change religion, or have no religion, while following UK law.",
  },
  {
    id: "values-006",
    topicId: "values",
    topic: "UK values and society",
    prompt: "Which statement best describes a democracy?",
    options: [
      "Leaders are chosen by inheritance only",
      "Citizens can help choose representatives through elections",
      "Courts make all government policy",
      "Newspapers appoint ministers",
    ],
    correctIndex: 1,
    explanation: "In a democracy, eligible citizens vote for representatives and can take part in public debate.",
  },
  {
    id: "history-001",
    topicId: "history",
    topic: "History and traditions",
    prompt: "In which year did the Battle of Hastings take place?",
    options: ["1066", "1215", "1485", "1688"],
    correctIndex: 0,
    explanation: "The Battle of Hastings took place in 1066 and led to Norman rule in England.",
  },
  {
    id: "history-002",
    topicId: "history",
    topic: "History and traditions",
    prompt: "Which document, agreed in 1215, limited the power of the monarch?",
    options: ["The Domesday Book", "Magna Carta", "The Act of Union", "The Reform Act"],
    correctIndex: 1,
    explanation: "Magna Carta was agreed in 1215 and became an important symbol of limits on royal power.",
  },
  {
    id: "history-003",
    topicId: "history",
    topic: "History and traditions",
    prompt: "Who was the first female Prime Minister of the UK?",
    options: ["Elizabeth Fry", "Margaret Thatcher", "Emmeline Pankhurst", "Mary Seacole"],
    correctIndex: 1,
    explanation: "Margaret Thatcher became the UK's first female Prime Minister in 1979.",
  },
  {
    id: "history-004",
    topicId: "history",
    topic: "History and traditions",
    prompt: "What happened in 1688 during the Glorious Revolution?",
    options: [
      "The Romans left Britain",
      "William and Mary were invited to take the throne",
      "The NHS was founded",
      "The first census was held",
    ],
    correctIndex: 1,
    explanation: "The Glorious Revolution led to William and Mary becoming joint monarchs and strengthened Parliament's role.",
  },
  {
    id: "history-005",
    topicId: "history",
    topic: "History and traditions",
    prompt: "Which saint is traditionally associated with England?",
    options: ["St Andrew", "St David", "St George", "St Patrick"],
    correctIndex: 2,
    explanation: "St George is the patron saint traditionally associated with England.",
  },
  {
    id: "history-006",
    topicId: "history",
    topic: "History and traditions",
    prompt: "Which war ended in Europe in 1945?",
    options: ["The Crimean War", "The First World War", "The Second World War", "The Falklands conflict"],
    correctIndex: 2,
    explanation: "The Second World War ended in Europe in 1945.",
  },
  {
    id: "history-007",
    topicId: "history",
    topic: "History and traditions",
    prompt: "What is Remembrance Day connected with?",
    options: [
      "Remembering people who died in wars",
      "Celebrating the start of spring",
      "Marking the monarch's birthday",
      "Opening Parliament after an election",
    ],
    correctIndex: 0,
    explanation: "Remembrance Day honours those who died in wars and is marked on 11 November.",
  },
  {
    id: "government-001",
    topicId: "government",
    topic: "Government and the law",
    prompt: "What are the two Houses of the UK Parliament?",
    options: [
      "The Cabinet and the Civil Service",
      "The House of Commons and the House of Lords",
      "The Supreme Court and the Crown Court",
      "The Welsh Senedd and the Scottish Parliament",
    ],
    correctIndex: 1,
    explanation: "The UK Parliament is made up of the House of Commons, the House of Lords, and the monarch.",
  },
  {
    id: "government-002",
    topicId: "government",
    topic: "Government and the law",
    prompt: "Who normally becomes Prime Minister after a UK general election?",
    options: [
      "The leader able to command confidence in the House of Commons",
      "The oldest member of the House of Lords",
      "The Speaker of the House of Commons",
      "The Chief Justice",
    ],
    correctIndex: 0,
    explanation: "The Prime Minister is usually the leader of the party that can command a majority in the House of Commons.",
  },
  {
    id: "government-003",
    topicId: "government",
    topic: "Government and the law",
    prompt: "What is an MP?",
    options: [
      "A Member of Parliament elected to represent a constituency",
      "A mayor appointed by the monarch",
      "A police officer in training",
      "A judge in the Supreme Court",
    ],
    correctIndex: 0,
    explanation: "MP stands for Member of Parliament. MPs represent constituencies in the House of Commons.",
  },
  {
    id: "government-004",
    topicId: "government",
    topic: "Government and the law",
    prompt: "Which age is generally required to vote in UK Parliamentary general elections?",
    options: ["16", "17", "18", "21"],
    correctIndex: 2,
    explanation: "For UK Parliamentary general elections, voters must generally be aged 18 or over and meet eligibility rules.",
  },
  {
    id: "government-005",
    topicId: "government",
    topic: "Government and the law",
    prompt: "Which country has a devolved parliament called the Scottish Parliament?",
    options: ["England", "Scotland", "Wales", "Northern Ireland"],
    correctIndex: 1,
    explanation: "Scotland has a devolved legislature known as the Scottish Parliament.",
  },
  {
    id: "government-006",
    topicId: "government",
    topic: "Government and the law",
    prompt: "What is the role of independent courts?",
    options: [
      "To apply the law without improper political influence",
      "To choose the Prime Minister",
      "To collect council tax",
      "To write political party manifestos",
    ],
    correctIndex: 0,
    explanation: "Independent courts help protect the rule of law by applying the law fairly.",
  },
  {
    id: "government-007",
    topicId: "government",
    topic: "Government and the law",
    prompt: "Which of these is a duty of local councils?",
    options: [
      "Running many local services such as waste collection",
      "Commanding the armed forces",
      "Setting the Bank of England base rate",
      "Appointing all MPs",
    ],
    correctIndex: 0,
    explanation: "Local councils provide many local services, including waste collection, planning, and some social services.",
  },
  {
    id: "government-008",
    topicId: "government",
    topic: "Government and the law",
    prompt: "What is the Cabinet?",
    options: [
      "Senior government ministers chosen by the Prime Minister",
      "All judges in England and Wales",
      "Every elected councillor in the UK",
      "A committee of newspaper editors",
    ],
    correctIndex: 0,
    explanation: "The Cabinet is made up of senior ministers who lead government departments and advise on policy.",
  },
  {
    id: "everyday-001",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "Which city is the capital of Wales?",
    options: ["Edinburgh", "Cardiff", "Belfast", "Manchester"],
    correctIndex: 1,
    explanation: "Cardiff is the capital city of Wales.",
  },
  {
    id: "everyday-002",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "Which service provides publicly funded healthcare across the UK?",
    options: ["The NHS", "The BBC", "The DVLA", "The National Trust"],
    correctIndex: 0,
    explanation: "The National Health Service, or NHS, provides publicly funded healthcare.",
  },
  {
    id: "everyday-003",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "Which of these is a UK public holiday in many parts of the country?",
    options: ["Thanksgiving Day", "Bastille Day", "Christmas Day", "Independence Day"],
    correctIndex: 2,
    explanation: "Christmas Day is a public holiday across the UK.",
  },
  {
    id: "everyday-004",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "What is the census used for?",
    options: [
      "Collecting information about the population",
      "Choosing the monarch",
      "Replacing general elections",
      "Setting football league results",
    ],
    correctIndex: 0,
    explanation: "The census collects population information that helps plan services such as schools, housing, and transport.",
  },
  {
    id: "everyday-005",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "Which country is not part of the United Kingdom?",
    options: ["Scotland", "Wales", "Northern Ireland", "The Republic of Ireland"],
    correctIndex: 3,
    explanation: "The UK is England, Scotland, Wales, and Northern Ireland. The Republic of Ireland is a separate country.",
  },
  {
    id: "everyday-006",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "What is the minimum school leaving age commonly stated for compulsory education in England?",
    options: ["12", "14", "16", "20"],
    correctIndex: 2,
    explanation: "Compulsory school age in England runs to 16, with further education or training participation requirements after that.",
  },
  {
    id: "everyday-007",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "Which organisation is the UK's public service broadcaster?",
    options: ["The BBC", "HMRC", "The NHS", "The Electoral Commission"],
    correctIndex: 0,
    explanation: "The BBC is the UK's public service broadcaster.",
  },
  {
    id: "everyday-008",
    topicId: "everyday-life",
    topic: "Everyday life in the UK",
    prompt: "What should someone usually do if they move home and are eligible to vote?",
    options: [
      "Register to vote at the new address",
      "Wait until the next census only",
      "Apply for a new passport immediately",
      "Contact the House of Lords",
    ],
    correctIndex: 0,
    explanation: "Eligible voters should keep their electoral registration up to date when they move address.",
  },
];

export const questions: Question[] = [...starterQuestions, ...handbookQuestions];
